spring:
  datasource:
    url: jdbc:mysql://localhost:20000/pickitalki?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul  # JSON 변환 시 KST 적
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul  # Hibernate가 KST로 저장하도록 설정


kakao:
  auth-url: "https://kauth.kakao.com/oauth/authorize"
  token-url: "https://kauth.kakao.com/oauth/token"
  user-info-url: "https://kapi.kakao.com/v2/user/me"
  redirect_uri: "http://localhost:8080/callback"
  client_id: "593bbcfa93f4286bf118f1e2d31891b8"


jwt:
  secret-key: "pikytalk-secure-connection-key-keep-friends-together!"
  access-expiration-time: 1800000  # 24?? (???)
  refresh-token-expiration : 604800000 # 7?

app:
  base-url: "http://ec2-52-79-242-171.ap-northeast-2.compute.amazonaws.com:8080"


